language: cpp
sudo: required
dist: trusty
compiler:
- clang
os:
- linux
- osx
before_install:
- echo $LANG
- echo $LC_ALL
- if [ $TRAVIS_OS_NAME == linux ]; then apt-get update && apt-get install libssl-dev unixodbc-dev; fi
- if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install openssl && brew link --force --overwrite openssl; fi
before_script:
- mkdir build
- cd build
script:
- cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_SHARED_LIBS=FALSE
- cmake --build . --target package --config RelWithDebInfo
